Shreeji818 patch 8
openmainframeproject/zorow pull request #43
Opened 2020-05-26 20:12 UTC by shreeji818

Sync up Db2 workflows with workflows in /IBM/Db2ZTools/DevOps repository

2020-05-26 20:32 UTC, Conner-IBM requested changes
Just to clarify, this is how DB2 is currently shipping these workflows? Having a binary pax instinctively feels off when hosting on github, as it makes it difficult to view or contribute to the source files. However if this is the format that has been provided by the DB2 middleware team, I think I can understand their intended usecase.

However, the currently included .DS_store files need to be removed from this commit.

2020-05-27 16:24 UTC, shreeji818 commented
Added .gitignore to ignore .DS_Store files in commit.

2020-05-27 17:16 UTC, shreeji818 commented
Removed .DS_Store files from commit. Please review.

2020-05-27 17:44 UTC, Conner-IBM approved these changes
DS_Store files where removed. 
We have discussed the approach about simply shipping pax files instead of readable files, and currently this is the approach DB2 is taking.
I think that the readme for this upper level directory could be improved to explain why these choices where made to help avoid confusion from anyone browsing this repository, aside from that cosmetic update- Looks good. So marking approved. Readme can be updated now or via git if preferred.

2020-05-27 17:44 UTC, Conner-IBM commented on provisioning-workflows/Db2/README.md
> +Various workflows that provide Db2 provisioning services. To provision a new Db2 subsystem (DataSharing or non Data Sharing) refer to Db2SystemServices. To provision Db2 Schema and sample database re
I think this file should be updated to explain the use of pax files in this repo.

2020-05-27 18:56 UTC, merged