Workflow Sample Working with Dataset
openmainframeproject/zorow pull request #9
Opened 2019-06-05 08:39 UTC by zhaocaih

Signed-off-by: Caihua Zhao <zhaocaih@cn.ibm.com>

2019-06-13 16:41 UTC, shreeji818 commented on zOSMF-Samples/workflow_sample_dataset.xml
> +        <workflowDescription>Sample that demonstrates working with a dataset and gether feedback for a step.</workflowDescription>
<workflowDescription>Sample that demonstrates working with a dataset and gather feedback for a step.</workflowDescription>

2019-06-13 16:43 UTC, shreeji818 requested changes
Please update copyright as mentioned in previous review.

2019-06-14 01:25 UTC, zhaocaih commented
I updated the copyright, please help review, thanks!

2019-06-14 07:39 UTC, zhaocaih commented
Updated the format, please review again, thanks.

2019-06-14 12:10 UTC, shreeji818 approved these changes

2019-06-14 12:11 UTC, merged

2019-06-18 03:34 UTC, zhaocaih commented
> Description for file is not right. It picked up the last comment regarding the copyright update.

I am not sure I understand this, do I need to take any actions here?